# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04user\"\x98\x02\n\x04User\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04guid\x18\x03 \x01(\t\x12\x10\n\x08isActive\x18\x04 \x01(\x08\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x05\x12\x10\n\x08\x65yeColor\x18\x07 \x01(\t\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x0e\n\x06gender\x18\t \x01(\t\x12\x0f\n\x07\x63ompany\x18\n \x01(\t\x12\r\n\x05\x65mail\x18\x0b \x01(\t\x12\r\n\x05phone\x18\x0c \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\r \x01(\t\x12\r\n\x05\x61\x62out\x18\x0e \x01(\t\x12\x12\n\nregistered\x18\x0f \x01(\t\x12\x10\n\x08latitude\x18\x10 \x01(\x01\x12\x11\n\tlongitude\x18\x11 \x01(\x01\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t25\n\x0bUserService\x12&\n\x08SendUser\x12\n.user.User\x1a\x0e.user.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=21
  _globals['_USER']._serialized_end=301
  _globals['_RESPONSE']._serialized_start=303
  _globals['_RESPONSE']._serialized_end=330
  _globals['_USERSERVICE']._serialized_start=332
  _globals['_USERSERVICE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
